services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: ghcr.io/bebeshka0/agent_project-api:${IMAGE_TAG:-latest}
    container_name: rag_api
    restart: always
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://postgres:mysecretpassword@db:5432/vector_db
      COLLECTION_NAME: ${COLLECTION_NAME:-ml_articles_collection}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-intfloat/multilingual-e5-base}
      XAI_API_KEY: ${XAI_API_KEY}
      XAI_BASE_URL: ${XAI_BASE_URL:-https://api.x.ai/v1}
      XAI_MODEL: ${XAI_MODEL:-grok-4-1-fast-non-reasoning}
      HF_HUB_DISABLE_XET: "1"
    depends_on:
      - db
    ports:
      - "8000:8000"

  ui:
    image: ghcr.io/bebeshka0/agent_project-ui:${IMAGE_TAG:-latest}
    container_name: rag_ui
    restart: always
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  pg_data:

